version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todo-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zrwmzw4umqy7"
s3_prefix = "todo-app"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
parameter_overrides = "AppName=\"TodoApp\" ClientDomains=\"http://todo-client-bucket.s3-website.eu-north-1.amazonaws.com, http://localhost:3001/\" AdminEmail=\"ahmed.bazzara@tretton37.com\" AddGroupsToScopes=\"false\""
