version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "todo-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-zrwmzw4umqy7"
s3_prefix = "todo-app"
region = "eu-north-1"
confirm_changeset = true
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]
image_repositories = []

