# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  todo-app

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Globals:
  Function:
    Environment:
      Variables:
        TABLE_NAME: ToDoTable

Resources:
  # This is an SNS Topic with all default configuration properties. To learn more about the available options, see
  # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sns-topic.html
  # SimpleTopic:
  #   Type: AWS::SNS::Topic
  ToDoApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ToDoApi
      StageName: dev
      # Auth:
      #   DefaultAuthorizer: MyLambdaTokenAuthorizer
      #   Authorizers:
      #     MyLambdaTokenAuthorizer:
      #       FunctionArn: !GetAtt MyAuthFunction.Arn
      Auth:
        DefaultAuthorizer: TodoAppCognitoAuthorizer
        Authorizers:
          TodoAppCognitoAuthorizer:
            UserPoolArn: !GetAtt TodoAppCognitoUserPool.Arn
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'content-type'"
        AllowOrigin: "'*'"
        AllowCredentials: "'*'"
      EndpointConfiguration:
        Type: REGIONAL

  ToDoTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
      TableName: ToDoTable
  # This is the Lambda function definition associated with the source code: sns-payload-logger.js. For all available properties, see
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  CreateListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      FunctionName: CreateListFunction
      Description: A Lambda function that creates a to-do list
      Runtime: nodejs12.x
      Handler: dist/createFunction/createFunction.createList
      Timeout: 10
      Events:
        CreateListEvent:
          Type: Api
          Properties:
            Path: /createList
            Method: post
            RestApiId:
              Ref: ToDoApi
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ToDoTable
  GetListsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      FunctionName: GetListsFunction
      Description: A Lambda function that gets all to-do lists
      Runtime: nodejs12.x
      Handler: dist/getFunction/getFunction.getLists
      Timeout: 10
      Events:
        GetListsEvent:
          Type: Api
          Properties:
            Path: /getLists
            Method: get
            RestApiId:
              Ref: ToDoApi

  TodoAppCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref TodoAppUserPool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false
  
  TodoAppCognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref TodoAppUserPool
      ClientName: !Ref TodoAppUserPoolClient
      GenerateSecret: false
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
        - aws.cognito.signin.user
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - http://localhost:3001/callback
      LogoutURLs:
        - http://localhost:3002/logout
  # local test sam local invoke -e ./src/handlers/get-lists-function/lambda_event.json GetListsFunction

  # SNSPayloadLogger:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     Description: A Lambda function that logs the payload of messages sent to an associated SNS topic.
  #     Runtime: nodejs12.x
  #     Handler: dist/handlers/sns-payload-logger.snsPayloadLoggerHandler
  #     # This property associates this Lambda function with the SNS topic defined above, so that whenever the topic
  #     # receives a message, the Lambda function is invoked
  #     Events:
  #       SNSTopicEvent:
  #         Type: SNS
  #         Properties:
  #           Topic: !Ref SimpleTopic
  #     MemorySize: 128
  #     Timeout: 100
  #     Policies:
  #       # Give Lambda basic execution Permission to the helloFromLambda
  #       - AWSLambdaBasicExecutionRole
