# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  create-lists-function

# Transform section specifies one or more macros that AWS CloudFormation uses to process your template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/transform-section-structure.html
Transform:
- AWS::Serverless-2016-10-31

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Globals:
  Function:
    Environment:
      Variables:
        TABLE_NAME: ToDoTable

Resources:
  ToDoApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ToDoApi
      StageName: dev
      EndpointConfiguration:
        Type: REGIONAL

  ToDoTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: Number
      TableName: ToDoTable
  # This is the Lambda function definition associated with the source code: sns-payload-logger.js. For all available properties, see
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  CreateListFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      FunctionName: CreateListFunction
      Description: A Lambda function that creates a to-do list
      Runtime: nodejs12.x
      Handler: create-list.createList
      Events:
        CreateListEvent:
          Type: Api
          Properties:
            Path: /createList
            Method: post
            RestApiId:
              Ref: ToDoApi
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ToDoTable
  