name: samdeploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: |
          echo "::set-output name=dir::$(yarn cache dir)"
          echo "::set-output name=version::$(yarn -v)"

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Install Packages
        run: yarn install --frozen-lockfile

      - name: Build and Transpile Code
        run: yarn run webpack

      - name: Build SAM Template
        run: sam build --use-container --template-file dist/template_prod.yml
      # - run: sam build --use-container --parameter-overrides AppName=TodoApp,ClientDomains=http://localhost:3001,http://todo-client-bucket.s3-website.eu-north-1.amazonaws.com,AdminEmail=ahmed.bazzara@tretton37.com,AddGroupsToScopes=false --template-file dist/template_prod.yml
      
      # - run: sam build --use-container --template-file dist/createFunction/template.yml
      # - run: sam build --use-container --template-file dist/getFunction/template.yml
      # - run: yarn run webpack && sam build --use-container --template-file ./handlers/create-list-function/.aws-sam/build/template.yaml
      - name: Deploy SAM Infrastructure
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset