name: samdeploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - run: yarn
      - run: yarn run webpack
      # - run: sam build --use-container
      - run: sam build --use-container --template-file dist/createFunction/template.yml
      - run: sam build --use-container --template-file dist/getFunction/template.yml
      # - run: yarn run webpack && sam build --use-container --template-file ./handlers/create-list-function/.aws-sam/build/template.yaml
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset